ktor:
    application:
        modules:
            - com.opeolluwa.ApplicationKt.module
    deployment:
        port: 8987
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: "g1cHifoXBSDNeLyjh2FBoQg9MAyl4KAEt4ymRLTy91BQa"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
